### ISSUE TITLE
thank you.

### ISSUE THREAD

**Issue by rowe-morehouse** [bacongravy/glitcheroo#1]
Hello Mr. Gravy. Can I call you Bacon? …

THANKS for this package! … super valuable to me right now, and I'm sure valuable to others. I have to use Glitch for a project, but the interface is super weird / unusable. So glad to be able to work in github then deploy to Glitch with your nifty tool. Cheers. :)

**Comment by bacongravy** [comment]
Thanks for the kind words, @rowe-morehouse ! I'm glad you found this useful.

I'm curious what your workflow is.  Do you use a local editor such as VS Code to make changes to your code and then push them to github?  When do you deploy to Glitch?

I have considered writing up a guide for how to use glitcheroo with GitHub Actions to automatically deploy changes on every commit and tag, would that be interesting to you?

**Comment by rowe-morehouse** [comment]
1) edit locally with sublime text
2) push to github from terminal
3) `npx glitcheroo deploy` — aliased to `ngd` :)

Yes, if it deployed automatically on `push` then that would be one less step!

**Comment by bacongravy** [comment]
@rowe-morehouse I created a GitHub repository to demonstrate how use `glitcheroo` with GitHub Actions to deploy to Glitch on every push: https://github.com/bacongravy/useful-insect
